In [8]:
import pandas as pd
from sqlalchemy import create_engine
import psycopg2
from time import time

In [9]:
pwd

'/home/lpop22/LKzoomcamp2025/2_docker_sql'

In [8]:
df = pd.read_csv('/home/lpop22/LKzoomcamp2025/data/inputs/yellow_tripdata_2021-01.csv.gz', nrows=100)

In [15]:
df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)

In [9]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [10]:
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [12]:
engine.connect()

In [16]:
pd.io.sql.get_schema(df, name='yellow_taxi_data')

'CREATE TABLE "yellow_taxi_data" (\n"VendorID" INTEGER,\n  "tpep_pickup_datetime" TIMESTAMP,\n  "tpep_dropoff_datetime" TIMESTAMP,\n  "passenger_count" INTEGER,\n  "trip_distance" REAL,\n  "RatecodeID" INTEGER,\n  "store_and_fwd_flag" TEXT,\n  "PULocationID" INTEGER,\n  "DOLocationID" INTEGER,\n  "payment_type" INTEGER,\n  "fare_amount" REAL,\n  "extra" REAL,\n  "mta_tax" REAL,\n  "tip_amount" REAL,\n  "tolls_amount" REAL,\n  "improvement_surcharge" REAL,\n  "total_amount" REAL,\n  "congestion_surcharge" REAL\n)'

In [30]:
df_iter = pd.read_csv('/home/lpop22/LKzoomcamp2025/data/inputs/yellow_tripdata_2021-01.csv.gz', iterator=True, chunksize=10000)

In [31]:
df = next(df_iter)

In [32]:
df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)

In [33]:
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [25]:
#%time df.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

CPU times: user 7.45 ms, sys: 0 ns, total: 7.45 ms
Wall time: 12.3 ms

100

In [35]:
while True:
    
    try:
        t_start = time()
    
        df = next(df_iter)
    
        df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
        df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)
    
        df.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')
    
        t_end = time()
    
        print('inserted another chunk, took %.3f second' % (t_end - t_start))
    except StopIteration:
        print("finished ingesting data into postgres db")
        break

inserted another chunk, took 0.475 second
inserted another chunk, took 0.425 second
inserted another chunk, took 0.442 second
inserted another chunk, took 0.468 second
inserted another chunk, took 0.429 second
inserted another chunk, took 0.424 second
inserted another chunk, took 0.460 second
inserted another chunk, took 0.435 second
inserted another chunk, took 0.417 second
inserted another chunk, took 0.438 second
inserted another chunk, took 0.444 second
inserted another chunk, took 0.424 second
inserted another chunk, took 0.427 second
inserted another chunk, took 0.439 second
inserted another chunk, took 0.486 second
inserted another chunk, took 0.437 second
inserted another chunk, took 0.426 second
inserted another chunk, took 0.463 second
inserted another chunk, took 0.424 second
inserted another chunk, took 0.416 second
inserted another chunk, took 0.403 second
inserted another chunk, took 0.474 second
inserted another chunk, took 0.429 second
inserted another chunk, took 0.413 second
inserted another chunk, took 0.406 second
inserted another chunk, took 0.449 second
inserted another chunk, took 0.409 second
inserted another chunk, took 0.409 second
inserted another chunk, took 0.418 second
inserted another chunk, took 0.450 second
inserted another chunk, took 0.429 second
inserted another chunk, took 0.403 second
inserted another chunk, took 0.413 second
inserted another chunk, took 0.457 second
inserted another chunk, took 0.421 second
inserted another chunk, took 0.415 second
inserted another chunk, took 0.411 second
inserted another chunk, took 0.458 second
inserted another chunk, took 0.424 second
inserted another chunk, took 0.418 second
inserted another chunk, took 0.436 second
inserted another chunk, took 0.477 second
inserted another chunk, took 0.420 second
inserted another chunk, took 0.422 second
inserted another chunk, took 0.460 second
inserted another chunk, took 0.414 second
inserted another chunk, took 0.425 second
inserted another chunk, took 0.425 second
inserted another chunk, took 0.451 second
inserted another chunk, took 0.422 second
inserted another chunk, took 0.424 second
inserted another chunk, took 0.408 second
inserted another chunk, took 0.471 second
inserted another chunk, took 0.426 second
inserted another chunk, took 0.407 second
inserted another chunk, took 0.422 second
inserted another chunk, took 0.459 second
inserted another chunk, took 0.426 second
inserted another chunk, took 0.419 second
inserted another chunk, took 0.416 second
inserted another chunk, took -0.663 second
inserted another chunk, took 0.436 second
inserted another chunk, took 0.412 second
inserted another chunk, took 0.416 second
inserted another chunk, took 0.463 second
inserted another chunk, took 0.409 second
inserted another chunk, took 0.419 second
inserted another chunk, took 0.423 second
inserted another chunk, took 0.480 second
inserted another chunk, took 0.436 second
inserted another chunk, took 0.441 second
inserted another chunk, took 0.444 second
inserted another chunk, took 0.418 second
inserted another chunk, took 0.475 second
inserted another chunk, took 0.457 second
inserted another chunk, took 0.422 second
inserted another chunk, took 0.485 second
inserted another chunk, took 0.427 second
inserted another chunk, took 0.430 second
inserted another chunk, took 0.424 second
inserted another chunk, took 0.407 second
inserted another chunk, took 0.480 second
inserted another chunk, took 0.421 second
inserted another chunk, took 0.435 second
inserted another chunk, took 0.480 second
inserted another chunk, took 0.411 second
inserted another chunk, took 0.409 second
inserted another chunk, took 0.439 second
inserted another chunk, took 0.426 second
inserted another chunk, took 0.483 second
inserted another chunk, took 0.418 second
inserted another chunk, took 0.485 second
inserted another chunk, took 0.417 second
inserted another chunk, took 0.478 second
inserted another chunk, took 0.418 second
inserted another chunk, took 0.453 second
inserted another chunk, took 0.417 second
inserted another chunk, took 0.458 second
inserted another chunk, took 0.411 second
inserted another chunk, took 0.420 second
inserted another chunk, took 0.419 second
inserted another chunk, took 0.428 second
inserted another chunk, took 0.453 second
inserted another chunk, took 0.411 second
inserted another chunk, took 0.418 second
inserted another chunk, took 0.443 second
inserted another chunk, took 0.485 second
inserted another chunk, took 0.422 second
inserted another chunk, took 0.423 second
inserted another chunk, took 0.450 second
inserted another chunk, took 0.428 second
inserted another chunk, took 0.453 second
inserted another chunk, took 0.421 second
inserted another chunk, took 0.437 second
inserted another chunk, took 0.431 second
inserted another chunk, took 0.483 second
inserted another chunk, took 0.423 second
inserted another chunk, took 0.420 second
inserted another chunk, took 0.422 second
inserted another chunk, took 0.441 second
inserted another chunk, took 0.481 second
inserted another chunk, took 0.408 second
inserted another chunk, took 0.412 second
inserted another chunk, took 0.422 second
inserted another chunk, took 0.487 second
inserted another chunk, took 0.439 second
inserted another chunk, took 0.464 second
inserted another chunk, took 0.408 second
inserted another chunk, took -0.723 second
inserted another chunk, took 0.457 second
inserted another chunk, took 0.384 second
inserted another chunk, took 0.384 second
inserted another chunk, took 0.403 second
inserted another chunk, took 0.387 second
inserted another chunk, took 0.431 second
inserted another chunk, took 0.391 second
finished ingesting data into postgres db

In [37]:
query = """
SELECT count(*) FROM yellow_taxi_data
"""

pd.read_sql(query, con = engine)

     count
0  1359765

In [13]:
df_zones = pd.read_csv('/home/lpop22/LKzoomcamp2025/data/inputs/taxi_zone_lookup.csv')

In [14]:
df_zones.to_sql(name='zones', con=engine, if_exists='replace')

265